pretrained_t2v_path: "showlab/show-1-base"
vid_name: "bird_forest"
logdir: "./outputs"
train_steps: 400
validation_steps: 100
seed: 12345
lr: 1e-4
num_inv_steps: 75

train_dataset:
  path: "video_images/${..vid_name}"
  prompt: "a bird is flying"
  n_sample_frame: 8
  sampling_rate: 1
  stride: 1

validation_sample_logger:
  prompts: [
    "a Phoenix is flying above lava",
    "a majestic dragon is flying in forest",
  ]
  clip_length: "${..train_dataset.n_sample_frame}"
  sample_seeds: [12345]
  num_inference_steps: 75
  guidance_scale: 9.0
  height: 40
  width: 64
